import type { OctopusConfig } from "./schema.js";

export const DEFAULT_CONFIG: OctopusConfig = {
	version: 1,
	server: {
		port: 18789,
		host: "127.0.0.1",
		transport: "auto",
	},
	browser: {
		headless: false,
		chromiumSandbox: undefined,
		provider: "auto",
		brightDataEnabled: true,
		decodoEnabled: true,
		solveCaptchas: true,
		captchaProvider: "2captcha",
		captchaTimeoutMs: 120000,
		persistCookies: true,
		sessionTtlHours: 168,
		autoFallbackOnBlock: true,
		blockFallbackProvider: "decodo",
		confirmBlockWithVision: true,
		blockResources: ["font"],
		blockTrackerDomains: true,
		humanBehavior: true,
		autoDismissPopups: true,
	},
	mascots: {
		defaultId: "pulpo-octavio",
	},
	ai: {
		default: "zhipu/glm-5.1",
		fallback: "openai/gpt-4.1",
		providers: {
			anthropic: {
				apiKey: "",
				baseUrl: "https://api.anthropic.com/v1",
				models: ["claude-opus-4-6", "claude-sonnet-4-6", "claude-haiku-4-5"],
			},
			openai: {
				apiKey: "",
				baseUrl: "https://api.openai.com/v1",
				authMode: "api-key",
				models: ["gpt-4.1", "gpt-4o", "gpt-4o-mini", "o3", "o4-mini"],
			},
			google: {
				apiKey: "",
				authMode: "api-key",
				models: ["gemini-2.5-pro", "gemini-2.5-flash"],
			},
			zhipu: {
				apiKey: "",
				mode: "coding-plan",
				models: ["glm-5.1", "glm-5", "glm-5-turbo", "glm-5v-turbo", "glm-4.6v"],
			},
			openrouter: {
				apiKey: "",
				baseUrl: "https://openrouter.ai/api/v1",
				models: [
					"openai/gpt-4.1",
					"anthropic/claude-sonnet-4-6",
					"google/gemini-2.5-pro",
				],
			},
			deepseek: {
				apiKey: "",
				baseUrl: "https://api.deepseek.com",
				models: ["deepseek-chat", "deepseek-reasoner"],
			},
			mistral: {
				apiKey: "",
				baseUrl: "https://api.mistral.ai/v1",
				models: ["mistral-large-3", "mistral-small-4", "codestral-25-08"],
			},
			xai: {
				apiKey: "",
				baseUrl: "https://api.x.ai/v1",
				models: ["grok-4.20-0309-reasoning", "grok-4-1-fast-reasoning"],
			},
			cohere: {
				apiKey: "",
				baseUrl: "https://api.cohere.com/v2",
				models: ["command-a-03-2025", "command-a-vision-07-2025"],
			},
			local: {
				baseUrl: "http://localhost:11434",
				models: ["llama3.1", "codellama", "mistral", "qwen2.5"],
			},
		},
		thinking: "medium",
		maxTokens: 16384,
	},
	channels: {
		whatsapp: { enabled: false },
		telegram: { enabled: false },
		discord: { enabled: false },
		slack: { enabled: false },
		teams: { enabled: false },
		signal: { enabled: false },
		wechat: { enabled: false },
		webchat: { enabled: true },
	},
	connection: {
		autoProxy: true,
		retryMaxAttempts: 5,
		retryBaseDelay: 1000,
		circuitBreakerThreshold: 5,
		healthCheckInterval: 30000,
		offlineQueueSize: 1000,
		preferIPv4: true,
	},
	memory: {
		enabled: true,
		shortTerm: {
			maxTokens: 8192,
			scratchPadSize: 2048,
			autoEviction: true,
		},
		longTerm: {
			backend: "sqlite-vss",
			vectorStore: {
				url: "",
				apiKey: "",
				collection: "octopus_memory",
				timeoutMs: 10000,
				maxRetries: 2,
				retryBaseDelayMs: 100,
			},
			importanceThreshold: 0.5,
			maxItems: 100000,
			episodic: {
				decayRate: 0.003,
				compressionAfter: "30d",
				maxAge: "365d",
			},
			semantic: {
				decayRate: 0.0001,
				contradictionCheck: true,
			},
			associative: {
				enabled: true,
				cascadeDepth: 2,
				cascadeThreshold: 0.8,
			},
		},
		consolidation: {
			trigger: "task-complete",
			idleInterval: "30m",
			batchSize: 50,
			extractFacts: true,
			extractEvents: true,
			extractProcedures: true,
			buildAssociations: true,
			compressAndDecay: true,
		},
		retrieval: {
			maxResults: 10,
			maxTokens: 2000,
			minRelevance: 0.6,
			weights: {
				relevance: 0.5,
				recency: 0.3,
				frequency: 0.2,
			},
		},
		embeddings: {
			enabled: false,
			provider: "auto",
			apiType: "openai",
			model: "",
			baseUrl: "",
			apiKey: "",
			apiKeyEnv: "",
			credentialsJson: "",
			task: "document",
			dimensions: 1024,
			maxBatchSize: 32,
			maxTextLength: 8000,
			cacheSize: 500,
			failureRetryMs: 60000,
		},
		retention: {
			enabled: false,
			cron: "30 3 * * *",
			unusedDays: 90,
			lowImportanceThreshold: 0.25,
			contradictionGraceDays: 14,
		},
	},
	skills: {
		enabled: true,
		autoCreate: true,
		autoImprove: true,
		forge: {
			complexityThreshold: 0.6,
			selfCritique: true,
			minQualityScore: 7,
			includeExamples: true,
			includeTemplates: true,
			includeAntiPatterns: true,
		},
		improvement: {
			triggerOnSuccessRate: 0.7,
			triggerOnRating: 3.5,
			reviewEveryNUses: 10,
			abTestMajorChanges: true,
			abTestSampleSize: 20,
		},
		loading: {
			maxTokenBudget: 3000,
			progressiveLevels: true,
			autoUnload: true,
			searchThreshold: 0.7,
		},
		registry: {
			path: "~/.octopus/skills",
			builtinSkills: [
				"general-reasoning",
				"code-generation",
				"writing",
				"research",
			],
		},
	},
	learning: {
		enabled: true,
		autoReflect: true,
		minConfidenceToStore: 0.65,
		minConfidenceToInject: 0.55,
		maxInsightsPerContext: 5,
		maxContextTokens: 1000,
		autoCreateSkills: true,
		minSimilarSuccessesForSkill: 3,
		retainFailedInsights: true,
	},
	plugins: {
		directories: ["~/.octopus/plugins"],
		builtin: ["productivity", "coding"],
	},
	storage: {
		backend: "sqlite",
		path: "~/.octopus/data/octopus.db",
		connectionString: "",
		ssl: false,
	},
	security: {
		encryptionKey: "",
		memoryApiKey: "",
		allowedPaths: ["~/Documents", "~/Desktop"],
		sandboxCommands: true,
	},
	tools: {
		disabled: [],
		iterationLimit: {
			enabled: true,
			maxIterations: 18,
		},
		timeouts: {
			defaultMs: 45000,
			longRunningMs: 90000,
			captchaMs: 150000,
			scrapingMs: 165000,
			byTool: {
				delegate_task: 300000,
			},
		},
	},
	mcp: {
		servers: {},
		autoDisabled: [],
	},
};

export function getDefaults(): OctopusConfig {
	return JSON.parse(JSON.stringify(DEFAULT_CONFIG));
}
