import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
	type MediaMetaItem,
	flushPendingMediaMetaSync,
	loadMediaMeta,
	purgeDegeneratePlaceholderImages,
	saveMediaMeta,
	setMediaMetaPathsForTests,
} from "../tools/media-meta-store.js";

function item(id: string, overrides: Partial<MediaMetaItem> = {}): MediaMetaItem {
	return {
		id,
		filename: `${id}.png`,
		mimetype: "image/png",
		size: 2048,
		createdAt: "2026-08-19T00:00:00.000Z",
		...overrides,
	};
}

describe("media-meta-store", () => {
	let dir: string;
	let metaPath: string;

	beforeEach(async () => {
		dir = await mkdtemp(join(tmpdir(), "octopus-media-store-"));
		metaPath = join(dir, "meta.json");
		setMediaMetaPathsForTests({ mediaDir: dir, metaPath });
	});

	afterEach(() => {
		rmSync(dir, { recursive: true, force: true });
		delete (globalThis as Record<string, unknown>).__octopusMediaDirForTests;
		delete (globalThis as Record<string, unknown>)
			.__octopusMediaMetaPathForTests;
	});

	it("flush escribe atómico (tmp + rename) y sin dejar tmp", async () => {
		const items = [item("aaaaaaaa-1111-2222-3333-444444444444")];
		await saveMediaMeta(items);
		flushPendingMediaMetaSync();

		const onDisk = JSON.parse(readFileSync(metaPath, "utf-8"));
		expect(onDisk).toHaveLength(1);
		expect(() => readFileSync(`${metaPath}.tmp`, "utf-8")).toThrow();
	});

	it("un meta corrupto en disco NO limpia el cache (antes: wipe → 404s masivos)", async () => {
		const items = [item("aaaaaaaa-1111-2222-3333-444444444444")];
		await saveMediaMeta(items);
		flushPendingMediaMetaSync();
		expect(loadMediaMeta()).toHaveLength(1);

		// Simula una escritura a medio hacer de otro proceso.
		writeFileSync(metaPath, '{"items": [{"id": "aa', "utf-8");

		const afterCorruption = loadMediaMeta();
		expect(afterCorruption).toHaveLength(1);
		expect(afterCorruption[0]?.id).toBe(
			"aaaaaaaa-1111-2222-3333-444444444444",
		);
	});

	it("reconcilia archivos huérfanos (>=1KB) al cargar, ignorando basura diminuta", async () => {
		const realId = "bbbbbbbb-1111-2222-3333-444444444444";
		const junkId = "cccccccc-1111-2222-3333-444444444444";
		writeFileSync(
			join(dir, `${realId}.png`),
			Buffer.alloc(4096, 7),
		);
		writeFileSync(join(dir, `${junkId}.png`), Buffer.alloc(70, 7));
		writeFileSync(metaPath, JSON.stringify([]), "utf-8");

		// La reconciliación corre en el primer load del proceso de test tras el reset.
		const items = loadMediaMeta();

		const ids = items.map((entry) => entry.id);
		expect(ids).toContain(realId);
		expect(ids).not.toContain(junkId);
		expect(items.find((entry) => entry.id === realId)?.description).toBe(
			"(recuperado del disco)",
		);
	});

	it("purgeDegeneratePlaceholderImages elimina placeholders y sus archivos", async () => {
		const good = item("dddddddd-1111-2222-3333-444444444444");
		const junk = item("eeeeeeee-1111-2222-3333-444444444444", {
			size: 70,
			description: "Generated by image-generator: generated.png",
		});
		writeFileSync(join(dir, junk.filename), Buffer.alloc(70, 1));
		await saveMediaMeta([good, junk]);
		flushPendingMediaMetaSync();

		const removed = await purgeDegeneratePlaceholderImages();
		flushPendingMediaMetaSync();

		expect(removed).toBe(1);
		const ids = loadMediaMeta().map((entry) => entry.id);
		expect(ids).toContain(good.id);
		expect(ids).not.toContain(junk.id);
	});
});
